---
include:
  - board: nice_nano_v2
    shield: tomak79_left
    artifact-name: tomak79_left
  - board: nice_nano_v2
    shield: tomak79_right
    artifact-name: tomak79_right
  - board: nice_nano_v2
    shield: tomak79_dongle
    artifact-name: tomak79_dongle
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: nice_nano_v2
    shield: tomak79_dongle_i2c_test
    artifact-name: tomak79_dongle_i2c_test
    snippet: zmk-usb-logging
