#!/usr/bin/env bash

zmk_config_root="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
zmk_repo_root_default="$(cd "$zmk_config_root/../zmk" 2>/dev/null && pwd)"
zmk_repo_root="${ZMK_REPO_ROOT:-$zmk_repo_root_default}"
zmk_codex_file="$zmk_config_root/codex.md"
zmk_repo_agents_file="${ZMK_AGENTS_FILE:-$zmk_repo_root/AGENTS.md}"
zmk_config_agents_file="$zmk_config_root/AGENTS.md"
zmk_workspace_path_default="$(cd "$zmk_config_root/.." && pwd)/tomak79.code-workspace"
zmk_workspace_path="${ZMK_WORKSPACE:-$zmk_workspace_path_default}"

zmk_source_line() {
  printf '[ -f "%s" ] && . "%s"\n' "$zmk_config_root/codex-shell.sh" "$zmk_config_root/codex-shell.sh"
}

zmk_require_repo() {
  if [ -z "$zmk_repo_root" ] || [ ! -d "$zmk_repo_root/.git" ]; then
    echo "zmk repo not found. Set ZMK_REPO_ROOT to your cloned zmk repository."
    return 1
  fi
}

sync_zmk_agents() {
  local tmp_file
  local target

  zmk_require_repo || return 1

  if [ ! -f "$zmk_codex_file" ]; then
    echo "codex.md not found: $zmk_codex_file"
    return 1
  fi

  tmp_file="$(mktemp)"

  {
    echo "# Local Codex Instructions"
    echo
    echo "This file is generated by \`zmk start\` from \`../zmk-config/codex.md\`."
    echo "Read the project status below before doing any work in this repository."
    echo
    cat "$zmk_codex_file"
  } > "$tmp_file"

  mkdir -p "$(dirname "$zmk_repo_agents_file")"
  mkdir -p "$(dirname "$zmk_config_agents_file")"

  for target in "$zmk_repo_agents_file" "$zmk_config_agents_file"; do
    if [ -f "$target" ] && cmp -s "$tmp_file" "$target"; then
      continue
    fi

    cp "$tmp_file" "$target"
    echo "Updated $target from $zmk_codex_file"
  done

  rm -f "$tmp_file"
}

pull_repo() {
  local repo_dir="$1"

  if [ ! -d "$repo_dir/.git" ]; then
    echo "Git repo not found: $repo_dir"
    return 1
  fi

  git -C "$repo_dir" pull
}

zmk_detect_shell_rc() {
  local shell_name

  shell_name="$(basename "${SHELL:-bash}")"

  case "$shell_name" in
    bash)
      echo "$HOME/.bashrc"
      ;;
    zsh)
      echo "$HOME/.zshrc"
      ;;
    *)
      echo "$HOME/.profile"
      ;;
  esac
}

zmk_append_source_line() {
  local rc_file="$1"
  local source_line

  source_line="$(zmk_source_line)"

  mkdir -p "$(dirname "$rc_file")"
  touch "$rc_file"

  if grep -Fqx "$source_line" "$rc_file"; then
    echo "Shell init already configured in $rc_file"
    return 0
  fi

  {
    echo
    echo "$source_line"
  } >> "$rc_file"

  echo "Added Codex shell init to $rc_file"
}

zmk_install_shell() {
  local rc_file
  local shell_name

  if [ -n "$1" ]; then
    zmk_append_source_line "$1"
    return
  fi

  shell_name="$(basename "${SHELL:-bash}")"

  case "$shell_name" in
    bash)
      zmk_append_source_line "$HOME/.bashrc" || return
      zmk_append_source_line "$HOME/.profile" || return
      ;;
    zsh)
      zmk_append_source_line "$HOME/.zshrc" || return
      ;;
    *)
      rc_file="$(zmk_detect_shell_rc)"
      zmk_append_source_line "$rc_file" || return
      ;;
  esac
}

append_zmk_codex_progress() {
  local progress
  local timestamp

  if [ ! -f "$zmk_codex_file" ]; then
    echo "codex.md not found: $zmk_codex_file"
    return 1
  fi

  echo
  read -r -p "Progress note for codex.md: " progress
  [ -n "$progress" ] || progress="No progress note provided."
  timestamp="$(date '+%Y-%m-%d %H:%M:%S %Z')"

  {
    echo
    echo "- [$timestamp] $progress"
  } >> "$zmk_codex_file"
}

commit_and_push_repo() {
  local repo_dir="$1"
  local default_msg="$2"
  local commit_msg="$3"

  cd "$repo_dir" || return 1

  if git diff --quiet && git diff --cached --quiet; then
    echo "No changes to commit in $repo_dir."
    return 0
  fi

  git status
  git add .
  git commit -m "${commit_msg:-$default_msg}" && git push
}

zmk_end() {
  local msg

  append_zmk_codex_progress || return
  sync_zmk_agents || return

  echo
  read -r -p "Commit message: " msg

  commit_and_push_repo "$zmk_config_root" "Update tomak79 codex notes" "$msg"
}

zmk() {
  case "$1" in
    start)
      pull_repo "$zmk_config_root" || return
      pull_repo "$zmk_repo_root" || return
      sync_zmk_agents || return

      if command -v code >/dev/null 2>&1; then
        code "$zmk_workspace_path"
      else
        echo "'code' command not found. Skipping VS Code launch."
      fi
      ;;

    end)
      zmk_end
      ;;

    status)
      zmk_require_repo || return
      echo "[zmk]"
      git -C "$zmk_repo_root" status
      echo
      echo "[zmk-config]"
      git -C "$zmk_config_root" status
      ;;

    pull)
      pull_repo "$zmk_config_root" || return
      pull_repo "$zmk_repo_root" || return
      sync_zmk_agents || return
      ;;

    sync-agents)
      sync_zmk_agents
      ;;

    shell-init)
      zmk_source_line
      ;;

    install-shell)
      zmk_install_shell "$2"
      ;;

    *)
      echo "Usage:"
      echo "  zmk start   # git pull + open VSCode workspace"
      echo "  zmk end     # append codex note + commit + push"
      echo "  zmk status  # show git status"
      echo "  zmk pull    # pull zmk-config + zmk, then sync AGENTS.md"
      echo "  zmk sync-agents # regenerate zmk/AGENTS.md from codex.md"
      echo "  zmk shell-init [rc-file]   # print shell init line"
      echo "  zmk install-shell [rc-file] # append shell init line"
      ;;
  esac
}

end() {
  zmk_end
}

alias start='zmk start'

if [ "${BASH_SOURCE[0]}" = "$0" ]; then
  zmk "$@"
fi
