CONFIG_ZMK_SPLIT=y
CONFIG_ZMK_SPLIT_BLE=y
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=y
CONFIG_USB_DEVICE_STACK=y
CONFIG_ZMK_USB=y
CONFIG_ZMK_RGB_UNDERGLOW=n
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_KSCAN=y
CONFIG_KSCAN=y
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y
